// composables/useBlog.ts
import { computed } from 'vue'

// Content collections are split per locale (see content.config.ts)
export const blogCollectionFor = (locale: string) => (locale === 'fa' ? 'blog_fa' : 'blog_en')

// Localized app route for a content item path (/en/blog/x -> /blog/x, /fa/blog/x -> /fa/blog/x)
export const usePostLink = () => {
  const localePath = useLocalePath()
  const postLink = (post: { path?: string }) =>
    localePath((post.path || '/').replace(/^\/(en|fa)/, ''))
  return postLink
}

// Branded cover image generated by scripts/generate-covers.mjs
export const coverFor = (post: { path?: string }) =>
  `/covers${post.path || ''}.svg`

export async function useBlog() {
  const { locale } = useI18n()
  const collection = blogCollectionFor(locale.value)

  // Get all posts
  const { data: posts } = await useAsyncData(`all-blog-posts-${locale.value}`, () =>
    queryCollection(collection)
      .order('date', 'DESC')
      .all()
  )

  // Get single post by content path (e.g. /en/blog/slug)
  const getPost = async (slug: string) => {
    const { data } = await useAsyncData(`blog-post-${slug}`, () =>
      queryCollection(collection).path(slug).first()
    )
    return data
  }

  // Search posts
  const searchPosts = (query: string) => {
    if (!posts.value) return []
    const q = query.toLowerCase()
    return posts.value.filter(p =>
      p.title?.toLowerCase().includes(q) ||
      p.description?.toLowerCase().includes(q) ||
      p.category?.toLowerCase().includes(q)
    )
  }

  // Get posts by category
  const getPostsByCategory = (category: string) => {
    if (!posts.value) return []
    return posts.value.filter(p => p.category === category)
  }

  // Get all categories
  const categories = computed(() => {
    const cats = new Set<string>()
    posts.value?.forEach(p => {
      if (p.category) cats.add(p.category)
    })
    return Array.from(cats)
  })

  return { posts, getPost, searchPosts, getPostsByCategory, categories }
}
