// utils/blog.ts — pure helpers shared by composables, pages and tests.

// Content collections are split per locale (see content.config.ts)
export const blogCollectionFor = (locale: string): 'blog_en' | 'blog_fa' =>
  locale === 'fa' ? 'blog_fa' : 'blog_en'

// Remove the content locale prefix: /en/blog/x -> /blog/x, /fa/blog/x -> /blog/x
export const stripLocalePrefix = (path: string): string => {
  const stripped = path.replace(/^\/(en|fa)/, '')
  return stripped.startsWith('/') ? stripped : `/${stripped}`
}

// Branded cover image generated by scripts/generate-covers.mjs
export const coverForPath = (contentPath: string): string => `/covers${contentPath}.svg`
